# Serial connection to Arduino (R4)
serial_port: "/dev/tty.usbmodem1101"   # USB serial device path
baud: 115200                             # Baudrate (match Arduino sketch; e.g. 921600)

# Physical layout (U-shape 20m total)
leds_per_meter: 60                       # LEDs per meter on the strip(s)
segments_m:                              # Segment lengths in meters
  left: 9.5
  bottom: 1.0
  right: 9.5
order: ["left_down", "bottom_right", "right_up"]   # Order along U-shape
reels: [5.0, 5.0, 5.0, 5.0]              # Physical reel lengths (m), optional
flip_reel: []                            # Optional: which reels are flipped


# Audio
audio:
  device: "default"                      # Output device id/name (pygame mixer)
  gain_master: -6.0                       # Master gain (dB)
  overrides: {}                           # Optional per-species gain/pan overrides


# Simulation + behavior
sim:
  chirp_interval_min_s: 3.0               # Min interval (sec) for an individual to chirp
  chirp_interval_max_s: 12.0              # Max interval (sec) for an individual to chirp
  max_concurrent_total: 24                # Max simultaneous chirps overall (real runner)
  max_concurrent_per_species: 12          # Max simultaneous chirps per species (real runner)
  active_species_count: 3                 # Number of species active at a time (randomly chosen)
