serial_port: "/dev/tty.usbmodem1101"
baud: 115200
leds_per_meter: 60
segments_m:
  left: 9.5
  bottom: 1.0
  right: 9.5
order: ["left_down", "bottom_right", "right_up"]
reels: [5.0, 5.0, 5.0, 5.0]
flip_reel: []
wave:
  speed_mps: 2.0
  tail_m: 0.8
  pause_ms: 900
  easing: "quad_out"
audio:
  device: "default"
  gain_master: -6.0
  overrides: {}
detect:
  cam:
    roi: [0.55, 0.15, 0.4, 0.7]
    angle_fire_deg: -25
    angle_release_deg: -15
    min_interval_ms: 1500
  mic:
    threshold_db: -12
    min_interval_ms: 1500
fallback_trigger: true

sim:
  kakon_mean_s: 8.0
  kakon_std_s: 2.0
  kakon_wave_speed_factor: 3.0
  chirp_interval_min_s: 3.0
  chirp_interval_max_s: 12.0
  max_concurrent_chirps: 3
