# *******************************************************************
# * Kusiro Art - Main Settings
# *******************************************************************

# --- Visual & Simulation Parameters ---
# Screen dimensions for the simulation window
view_width: 1200
view_height: 400

# The width and height of the waterway area in the physical model (in meters)
# This should roughly match the coordinate range in the layout file.
model_width: 22.0
model_height: 2.0

# --- Layout & Sound ---
# Name of the ukidama (floating ball) position file in assets/data/
ukidama_layout_file: "kusiro_layout.csv"

# Path to the directory containing insect sound files
sound_dir: "assets/data/sound/trimmed"

# --- Lighting & Sound Parameters ---
# Overall brightness of the lights (0.0 to 1.0)
global_brightness: 0.7

# Base color for the ukidama lights (R, G, B)
base_color: [170, 220, 255] # A pale, watery blue

# --- Flickering Effect (Perlin Noise) ---
# Controls the speed of the brightness flickering. Higher is faster.
noise_speed: 0.1
# The range of brightness variation. 0.5 means brightness can vary by +/- 50%.
noise_strength: 0.6
# The "zoom" level of the noise pattern. Smaller values create smoother, slower changes.
noise_scale: 0.5

# --- Sound Playback ---
# The probability of a new sound starting on any given frame.
# 0.01 means about a 60% chance of a new sound every second at 60fps.
sound_start_probability: 0.01
# Maximum number of insect sounds that can be played simultaneously.
max_concurrent_sounds: 5

# ===================================================================
# === HARDWARE SETTINGS (for main_real.py)
# ===================================================================
# Serial port for the Arduino/controller
serial_port: "/dev/tty.usbmodemXXXX"
baud_rate: 921600
# The total number of LEDs in the physical installation.
# This MUST match the number of ukidamas in the layout file.
num_physical_leds: 225
